services:
  redis:
    image: redis:alpine
    networks:
      - nodehistj
    healthcheck:
      test: redis-cli ping || exit 1
      start_period: 30s
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  redpanda:
    image: redpandadata/redpanda
    restart: unless-stopped
    hostname: redpanda
    networks:
      - nodehistj
    command:
      - redpanda start
        --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
        --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 3
  postgres:
    image: postgres:alpine
    networks:
      - nodehistj
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      - ./pgsql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: pg_isready -U postgres || exit 1
      start_period: 30s
      interval: 5s
      timeout: 10s
      retries: 5

  # Сервис загрузки файлов nodelist с FTP
  # Основные зависимости: MinIO, Kafka
  nodehistj-download-nodelists:
    image: gavrilovegor519/nodehistj-download-nodelists:master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: nodehistj-download-nodelists
        SKIP_TESTS: "true"
    networks:
      - nodehistj
    labels:
      - "traefik.enable=false"
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=redpanda:9092
      - S3_URL=${S3_URL}
      - S3_USER=${S3_USER}
      - S3_PASSWORD=${S3_PASSWORD}
      - S3_BUCKET=${S3_BUCKET}
    depends_on:
      redpanda:
        condition: service_healthy

  # Сервис работы с историческими данными nodelist
  # Основные зависимости: MinIO, Kafka, PostgreSQL, Redis
  nodehistj-historic-nodelists:
    image: gavrilovegor519/nodehistj-historic-nodelists:master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: nodehistj-historic-nodelists
        SKIP_TESTS: "true"
      secrets:
        - github_username
        - github_token
    networks:
      - nodehistj
      - traefik
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=redpanda:9092
      - REDIS_HOST=redis
      - S3_URL=${S3_URL}
      - S3_USER=${S3_USER}
      - S3_PASSWORD=${S3_PASSWORD}
      - S3_BUCKET=${S3_BUCKET}
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    labels:
      - "traefik.http.routers.historic.rule=Host(`${DOMAIN}`) && PathPrefix(`/historic`)"
      - "traefik.http.routers.historic.entrypoints=websecure"
      - "traefik.http.routers.historic.tls.certresolver=myresolver"
      - "traefik.http.routers.historic.tls.domains[0].main=${DOMAIN}"
    depends_on:
      redpanda:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Сервис работы с актуальными данными nodelist
  # Основные зависимости: MinIO, Kafka, PostgreSQL, Redis
  nodehistj-newest-nodelists:
    image: gavrilovegor519/nodehistj-newest-nodelists:master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: nodehistj-newest-nodelists
        SKIP_TESTS: "true"
      secrets:
        - github_username
        - github_token
    networks:
      - nodehistj
      - traefik
    expose:
      - 8080
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=redpanda:9092
      - REDIS_HOST=redis
      - S3_URL=${S3_URL}
      - S3_USER=${S3_USER}
      - S3_PASSWORD=${S3_PASSWORD}
      - S3_BUCKET=${S3_BUCKET}
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    labels:
      - "traefik.http.routers.newest.rule=Host(`${DOMAIN}`) && PathPrefix(`/newest`)"
      - "traefik.http.routers.newest.entrypoints=websecure"
      - "traefik.http.routers.newest.tls.certresolver=myresolver"
      - "traefik.http.routers.newest.tls.domains[0].main=${DOMAIN}"
    depends_on:
      redpanda:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Сервис сравнения исторических и актуальных данных
  # Основные зависимости: Kafka, PostgreSQL, Redis
  nodehistj-history-diff:
    image: gavrilovegor519/nodehistj-history-diff:master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: nodehistj-history-diff
        SKIP_TESTS: "true"
      secrets:
        - github_username
        - github_token
    networks:
      - nodehistj
      - traefik
    expose:
      - 8080
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=redpanda:9092
      - REDIS_HOST=redis
      - S3_URL=${S3_URL}
      - S3_USER=${S3_USER}
      - S3_PASSWORD=${S3_PASSWORD}
      - S3_BUCKET=${S3_BUCKET}
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    labels:
      - "traefik.http.routers.history-diff.rule=Host(`${DOMAIN}`) && PathPrefix(`/diff`)"
      - "traefik.http.routers.history-diff.entrypoints=websecure"
      - "traefik.http.routers.history-diff.tls.certresolver=myresolver"
      - "traefik.http.routers.history-diff.tls.domains[0].main=${DOMAIN}"
    depends_on:
      redpanda:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

secrets:
  github_username:
    environment: GITHUB_USERNAME
  github_token:
    environment: GITHUB_TOKEN

networks:
  nodehistj:
    driver: bridge
  traefik:
    external: true

volumes:
  postgres_storage:
  redpanda_data:
